version: '3'
services:
  api:
    container_name: epicprompts
    image: epicprompts
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    environment:
      PORT: 8080
    env_file:
      - .env
    ports:
      - 8080:8080
  db:
    image: postgres
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: epicprompts
      POSTGRES_PASSWORD: ep1234
      POSTGRES_DB: epicprompts